language: rust
rust:
  - 1.45.0
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly

  include:
    - name: 'Rust: lint with Clippy'
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy
