# Colour output

[[cmd]]
shell = "dog dns.google --colour=always"
stdout = { string = "\u001B[1;32mA\u001B[0m \u001B[1;34mdns.google.\u001B[0m" }
stderr = { empty = true }
status = 0
tags = [ "live", "google" ]

[[cmd]]
shell = "dog dns.google"
stdout = { string = "A dns.google." }
stderr = { empty = true }
status = 0
tags = [ "live", "google" ]

[[cmd]]
shell = "dog dns.google --colour=never"
stdout = { string = "A dns.google." }
stderr = { empty = true }
status = 0
tags = [ "live", "google" ]


# Default record type and transport

[[cmd]]
shell = "dog dns.google -U"
stdout = { string = "A dns.google." }
stderr = { empty = true }
status = 0
tags = [ "live", "google" ]

[[cmd]]
shell = "dog A dns.google"
stdout = { string = "A dns.google." }
stderr = { empty = true }
status = 0
tags = [ "live", "google" ]

[[cmd]]
shell = "dog A dns.google --time"
stdout = { string = "Ran in" }
stderr = { empty = true }
status = 0
tags = [ "live", "google" ]


# Network errors

[[cmd]]
shell = "dog A dns.google @non.exist --time"
stdout = { string = "Ran in" }
stderr = { string = "Error [network]" }
status = 1
tags = [ "live", "google" ]
