# EUI48 record successes

[[cmd]]
name = "Running with ‘eui48.example’ prints the correct EUI48 record"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 EUI48 eui48.example"
stdout = { file = "outputs/eui48.example.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ "eui48", "madns" ]


# EUI48 record invalid packets

[[cmd]]
name = "Running with ‘too-long.eui48.invalid’ displays a record length error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 EUI48 too-long.eui48.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: record length should be 6, got 7" }
status = 1
tags = [ "eui48", "madns" ]

[[cmd]]
name = "Running with ‘too-short.eui48.invalid’ displays a record length error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 EUI48 too-short.eui48.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: record length should be 6, got 5" }
status = 1
tags = [ "eui48", "madns" ]

[[cmd]]
name = "Running with ‘empty.eui48.invalid’ displays a record length error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 EUI48 empty.eui48.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: record length should be 6, got 0" }
status = 1
tags = [ "eui48", "madns" ]

[[cmd]]
name = "Running with ‘incomplete.eui48.invalid’ displays a protocol error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 EUI48 incomplete.eui48.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "eui48", "madns" ]
