# OPENPGPKEY record successes

[[cmd]]
name = "Running with ‘openpgpkey.example’ prints the correct OPENPGPKEY record"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 OPENPGPKEY openpgpkey.example"
stdout = { file = "outputs/openpgpkey.example.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ "openpgpkey", "madns" ]


# OPENPGPKEY record invalid packets

[[cmd]]
name = "Running with ‘empty.openpgpkey.invalid’ displays a record length error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 OPENPGPKEY empty.openpgpkey.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: record length should be at least 1, got 0" }
status = 1
tags = [ "openpgpkey", "madns" ]

[[cmd]]
name = "Running with ‘incomplete.openpgpkey.invalid’ displays a protocol error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 OPENPGPKEY incomplete.openpgpkey.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "openpgpkey", "madns" ]
