# TXT record successes

[[cmd]]
name = "Running with ‘txt.example’ prints the correct TXT record"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 TXT txt.example"
stdout = { file = "outputs/txt.example.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ "txt", "madns" ]


# TXT record successes (JSON)

[[cmd]]
name = "Running with ‘txt.example’ prints the correct TXT record structure"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 TXT txt.example --json | jq"
stdout = { file = "outputs/txt.example.json" }
stderr = { empty = true }
status = 0
tags = [ "txt", "madns", "json" ]


# TXT record invalid packets

[[cmd]]
name = "Running with ‘empty.txt.invalid’ displays a protocol error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 TXT empty.txt.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "txt", "madns" ]

[[cmd]]
name = "Running with ‘incomplete.txt.invalid’ displays a protocol error"
shell = "dog --colour=always --tcp @madns.binarystar.systems:5301 TXT incomplete.txt.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "txt", "madns" ]
